# Numpy

In [6]:
import numpy as np
l = np.array([1,2,3,4])
print(l,',,,',l.shape)
print(l.reshape((2,2)),',,,',l.reshape((2,2)).shape)

[1 2 3 4] ,,, (4,)
[[1 2]
 [3 4]] ,,, (2, 2)


In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10).reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Q: Create the following array:

 array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [14]:
(np.arange(1,21)*2).reshape((4,5))

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

Q: Create matrix and access rows and columns

create a 4x5 array of even numbers: 10, 12, 14, …
extract third column<br>
set the fourth row to 1,2,3,4,5

In [20]:
l = np.arange(10,50,2).reshape((4,5))
print('l:',l)
print('\n')
print('l[:,2]: ',l[:,2])
print('\n')
l[3] = [1,2,3,4,5]
print('mod l:',l)

l: [[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


l[:,2]:  [14 24 34 44]


mod l: [[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [ 1  2  3  4  5]]


In [26]:
print(np.sum(l))
print(np.mean(l))
print(np.percentile(l,0.25))
print(np.median(l))
print(np.std(l))

375
18.75
1.0475
19.0
11.797775213996918


# Pandas

In [39]:
import pandas as pd

In [40]:
p = pd.Series( [ 'USA', 'CANADA', 'AUSTRALIA', 'INDIA'],
                 index = ['usa', 'can', 'aus', 'ind'])
p

usa          USA
can       CANADA
aus    AUSTRALIA
ind        INDIA
dtype: object

In [41]:
p.values

array(['USA', 'CANADA', 'AUSTRALIA', 'INDIA'], dtype=object)

In [42]:
p.index

Index(['usa', 'can', 'aus', 'ind'], dtype='object')

In [43]:
p=='USA'

usa     True
can    False
aus    False
ind    False
dtype: bool

**DataFrames**

In [44]:
df = {'ca': [35, 37, 38], 'tx': [23, 24, 26], 'md': [5,5,6]}
p = pd.DataFrame(df)
print('population:\n', p, '\n')

population:
    ca  tx  md
0  35  23   5
1  37  24   5
2  38  26   6 



In [45]:
p = pd.DataFrame(df, index = [2010,2012,2014])
print('population:\n', p, '\n')

population:
       ca  tx  md
2010  35  23   5
2012  37  24   5
2014  38  26   6 



Q: Create a dataframe of (at least 4) countries, with 2 variables: population and capital. Country name should be the index.

In [46]:
df = {'population':[100,80,100,1000],'capital':['c1','c2','c3','c4']}
df = pd.DataFrame(df,index=['USA','CANADA','RUSSIA','CHINA'])
df

population capital
USA            100      c1
CANADA          80      c2
RUSSIA         100      c3
CHINA         1000      c4

In [48]:
df = pd.read_csv('https://bitbucket.org/otoomet/lecturenotes/raw/master/data/gwbush-approval.csv',sep='\t')
print(df.shape)
df.head()

(31, 4)


date  approve  disapprove  dontknow
0  2001 Dec 14-16       86          11         3
1    2001 Dec 6-9       86          10         4
2  2001 Nov 26-27       87           8         5
3   2001 Nov 8-11       87           9         4
4    2001 Nov 2-4       87           9         4

In [50]:
df['approve'].head()

0    86
1    86
2    87
3    87
4    87
Name: approve, dtype: int64

In [56]:
df[df['approve']>86].shape

(7, 4)

In [55]:
df[(df['approve']<86) | (df['approve']>89)].shape

(22, 4)

Q: How many polls in the data show the president’s approval rate at least 88%? At which dates are those polls conducted?

In [60]:
df[df['approve']>=88][['date','approve']]

date  approve
5  2001 Oct 19-21       88
6  2001 Oct 11-14       89
8  2001 Sep 21-22       90

**Indexing**

In [61]:
data = pd.DataFrame({"capital":["Kuala Lumpur", "Jakarta", "Phnom Penh"],
                     "population":[32.7, 267.7, 15.3]},  # in millions
                    index=["MY", "ID", "KH"])
data

capital  population
MY  Kuala Lumpur        32.7
ID       Jakarta       267.7
KH    Phnom Penh        15.3

In [62]:
data.iloc[2]  # 3rd row, as series

capital       Phnom Penh
population          15.3
Name: KH, dtype: object

In [63]:
data.iloc[[2]]  # 3rd row, as data frame

capital  population
KH  Phnom Penh        15.3

In [64]:
data.iloc[2,1]  # 3rd row, 2nd column, as a number

15.3

In [65]:
data.loc["MY","capital"]  # Malaisian capital

'Kuala Lumpur'

In [66]:
data.loc[["KH", "ID"], ["population", "capital"]]
                          # Extract a sub-dataframe

population     capital
KH        15.3  Phnom Penh
ID       267.7     Jakarta

In [67]:
data["capital"]["MY"]

'Kuala Lumpur'

In [68]:
data["temperature"] = [27.7, 26.1, 26.6]  # daily mean, January
data

capital  population  temperature
MY  Kuala Lumpur        32.7         27.7
ID       Jakarta       267.7         26.1
KH    Phnom Penh        15.3         26.6

In [70]:
#Explicit copy is not needed before you start modifying data, you can do various filtering steps without .copy as long as you make the copy before modifications.
large = data[data.population > 20].copy()
large

capital  population  temperature
MY  Kuala Lumpur        32.7         27.7
ID       Jakarta       267.7         26.1